### ISSUE TITLE
sqlite3.OperationalError: no such table: blockchain

### ISSUE THREAD

**Issue by bombrom** [TreeCityWes/XenBlocksExplorer#1]
After executing: python indexer.py

Traceback (most recent call last):
  File "...XenBlocksExplorer/indexer.py", line 88, in <module>
    main()
  File "...XenBlocksExplorer/indexer.py", line 42, in main
    source_cursor.execute("SELECT records_json FROM blockchain")
sqlite3.OperationalError: no such table: blockchain

File blockchain.db in directory:
...XenBlocksExplorer $ ls
README.md  blockchain.db  blockchainindex.db  chaincheck.py  chart.py  indexer.py

**Comment by TreeCityWes** [comment]
You'll need to get the updated syncnode from the XenMiner github

**Comment by bombrom** [comment]
Works after:
.../xenminer $ python syncnode.py <ethereum_address> (after sync and validating of 11500 blocks)
.../xenminer $ python indexer.py (with XenBlocksExplorer files in xenminer directory, where blockchain.db is)
.../xenminer $ python chaincheck.py
Thanks!
